app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/springboot-jdbc
      username: postgres
      password: 'postgres'
      pool-size: 30


server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/springboot-jdbc
    user: postgres
    password: 'postgres'
    group: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
