### Get movies list
GET http://localhost:8080/api/v1/movies
Accept: application/json

### Get movie by id
GET http://localhost:8080/api/v1/movies/1
Accept: application/json

### Add new movie
POST http://localhost:8080/api/v1/movies/1
Accept: application/json
Content-Type: application/json

{
  "name": "Titanic",
  "released_date": "1990-01-02"
}

### Delete movie by id
DELETE http://localhost:8080/api/v1/movies/1
Accept: application/json
